using Terraria.ID;

namespace WotTK.Common.Sets;

public static class NPCSets
{
    public static readonly (int, int)[] Level = NPCID.Sets.Factory.CreateCustomSet(
        (0, 0),
        // Slimes
        NPCID.BlueSlime,
        (1, 3),
        NPCID.SlimeSpiked,
        (1, 3),
        NPCID.SlimeRibbonGreen,
        (1, 3),
        NPCID.SlimeRibbonRed,
        (1, 3),
        NPCID.SlimeRibbonWhite,
        (1, 3),
        NPCID.SlimeRibbonYellow,
        (1, 3),
        NPCID.DungeonSlime,
        (15, 20),
        NPCID.GoldenSlime,
        (1, 3),
        NPCID.IceSlime,
        (1, 3),
        NPCID.IlluminantSlime,
        (1, 3),
        NPCID.LavaSlime,
        (1, 3),
        NPCID.RainbowSlime,
        (1, 3),
        NPCID.PurpleSlime,
        (1, 3),
        NPCID.SpikedIceSlime,
        (1, 3),
        NPCID.SpikedJungleSlime,
        (1, 3),
        NPCID.UmbrellaSlime,
        (1, 3),
        // Zombies
        NPCID.Zombie,
        (4, 6),
        NPCID.ZombieDoctor,
        (4, 6),
        NPCID.ZombieElf,
        (4, 6),
        NPCID.ZombieEskimo,
        (4, 6),
        NPCID.ZombieMerman,
        (4, 6),
        NPCID.ZombieMushroom,
        (4, 6),
        NPCID.ZombiePixie,
        (4, 6),
        NPCID.ZombieRaincoat,
        (4, 6),
        NPCID.ZombieSuperman,
        (4, 6),
        NPCID.ZombieXmas,
        (4, 6),
        NPCID.ZombieElfBeard,
        (4, 6),
        NPCID.ZombieElfGirl,
        (4, 6),
        NPCID.ZombieMushroomHat,
        (4, 6),
        NPCID.ArmedZombie,
        (4, 6),
        NPCID.BaldZombie,
        (4, 6),
        NPCID.BloodZombie,
        (10, 15),
        NPCID.FemaleZombie,
        (4, 6),
        NPCID.MaggotZombie,
        (4, 6),
        NPCID.PincushionZombie,
        (4, 6),
        NPCID.SlimedZombie,
        (4, 6),
        NPCID.SwampZombie,
        (4, 6),
        NPCID.TorchZombie,
        (4, 6),
        NPCID.TwiggyZombie,
        (4, 6),
        NPCID.ArmedTorchZombie,
        (4, 6),
        NPCID.ArmedZombieCenx,
        (4, 6),
        NPCID.ArmedZombieEskimo,
        (4, 6),
        NPCID.ArmedZombiePincussion,
        (4, 6),
        NPCID.ArmedZombieSlimed,
        (4, 6),
        NPCID.ArmedZombieSwamp,
        (4, 6),
        NPCID.ArmedZombieTwiggy,
        (4, 6),
        NPCID.GiantWormHead,
        (5, 10),
        // Underground
        NPCID.BlueJellyfish,
        (5, 10),
        NPCID.DiggerHead,
        (5, 10),
        NPCID.PossessedArmor,
        (5, 10),
        NPCID.ToxicSludge,
        (5, 10),
        NPCID.GreenJellyfish,
        (5, 10),
        // Caverns
        NPCID.Crawdad,
        (11, 15),
        NPCID.Salamander,
        (11, 15),
        NPCID.Salamander2,
        (11, 15),
        NPCID.Salamander3,
        (11, 15),
        NPCID.Salamander4,
        (11, 15),
        NPCID.Salamander5,
        (11, 15),
        NPCID.Salamander6,
        (11, 15),
        NPCID.Salamander7,
        (11, 15),
        NPCID.Salamander8,
        (11, 15),
        NPCID.Salamander9,
        (11, 15),
        NPCID.GiantShelly,
        (11, 15),
        NPCID.GiantShelly2,
        (11, 15),
        NPCID.UndeadMiner,
        (11, 15),
        NPCID.Tim,
        (11, 15),
        NPCID.Nymph,
        (11, 15),
        NPCID.CochinealBeetle,
        (11, 15),
        NPCID.ArmoredSkeleton,
        (11, 15),
        NPCID.SkeletonArcher,
        (11, 15),
        NPCID.GiantBat,
        (11, 15),
        NPCID.AnglerFish,
        (11, 15),
        // Ocean
        NPCID.PinkJellyfish,
        (9, 12),
        NPCID.Crab,
        (9, 12),
        NPCID.Squid,
        (9, 12),
        NPCID.SeaSnail,
        (9, 12),
        NPCID.Shark,
        (9, 12),
        // Desert
        NPCID.SandSlime,
        (3, 6),
        NPCID.Vulture,
        (3, 4),
        NPCID.Antlion,
        (6, 7),
        NPCID.FlyingAntlion,
        (6, 9),
        NPCID.Mummy,
        (35, 40),
        // Jungle
        NPCID.JungleBat,
        (16, 20),
        NPCID.Piranha,
        (16, 20),
        NPCID.Snatcher,
        (16, 20),
        NPCID.DoctorBones,
        (16, 20),
        NPCID.Derpling,
        (16, 20),
        NPCID.GiantTortoise,
        (35, 40),
        NPCID.GiantFlyingFox,
        (16, 20),
        NPCID.AnglerFish,
        (16, 20),
        NPCID.Arapaima,
        (16, 20),
        NPCID.AngryTrapper,
        (35, 40),
        // Snow Biome
        NPCID.IceElemental,
        (13, 16),
        NPCID.Wolf,
        (13, 16),
        NPCID.IceGolem,
        (13, 16),
        // Crimson,
        NPCID.BloodCrawler,
        (21, 25),
        NPCID.BloodCrawlerWall,
        (21, 25),
        NPCID.FaceMonster,
        (21, 25),
        NPCID.Crimera,
        (21, 25),
        NPCID.Herpling,
        (21, 25),
        NPCID.Crimslime,
        (21, 25),
        NPCID.BloodJelly,
        (21, 25),
        NPCID.BloodFeeder,
        (21, 25),
        NPCID.BloodMummy,
        (35, 40),
        // Corruption
        NPCID.EaterofSouls,
        (21, 25),
        NPCID.CorruptGoldfish,
        (21, 25),
        NPCID.DevourerHead,
        (21, 25),
        NPCID.Corruptor,
        (21, 25),
        NPCID.CorruptSlime,
        (21, 25),
        NPCID.Slimer,
        (21, 25),
        NPCID.DarkMummy,
        (21, 25),
        // Dungeon
        NPCID.AngryBones,
        (30, 35),
        NPCID.AngryBonesBig,
        (30, 35),
        NPCID.AngryBonesBigHelmet,
        (25, 32),
        NPCID.AngryBonesBigMuscle,
        (25, 32),
        NPCID.DarkCaster,
        (25, 32),
        NPCID.CursedSkull,
        (25, 32),
        NPCID.GiantCursedSkull,
        (25, 32),
        NPCID.BlueArmoredBones,
        (25, 32),
        NPCID.BlueArmoredBonesMace,
        (25, 32),
        NPCID.BlueArmoredBonesSword,
        (25, 32),
        NPCID.BlueArmoredBonesNoPants,
        (25, 32),
        NPCID.RustyArmoredBonesAxe,
        (25, 32),
        NPCID.RustyArmoredBonesFlail,
        (25, 32),
        NPCID.RustyArmoredBonesSword,
        (25, 32),
        NPCID.RustyArmoredBonesSwordNoArmor,
        (25, 32),
        NPCID.HellArmoredBones,
        (25, 32),
        NPCID.HellArmoredBonesMace,
        (25, 32),
        NPCID.HellArmoredBonesSword,
        (45, 50),
        NPCID.HellArmoredBonesSpikeShield,
        (50, 55),
        NPCID.Paladin,
        (60, 65),
        NPCID.Necromancer,
        (45, 50),
        NPCID.NecromancerArmored,
        (25, 32),
        NPCID.RaggedCaster,
        (25, 32),
        NPCID.RaggedCasterOpenCoat,
        (45, 50),
        NPCID.DiabolistRed,
        (45, 50),
        NPCID.DiabolistWhite,
        (45, 50),
        NPCID.SkeletonCommando,
        (45, 50),
        NPCID.SkeletonSniper,
        (45, 50),
        NPCID.TacticalSkeleton,
        (45, 50),
        NPCID.BoneLee,
        (45, 50),
        NPCID.DungeonSpirit,
        (45, 50)
    );
}
